apiVersion: v1
kind: Service
metadata:
  name: accounts-application-service
  namespace: workshop
spec:
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
  selector:
    app: accounts-application
  type: ClusterIP