apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-application-config-map
  namespace: workshop
data:
  application.yml: |-
    server:
      port: 8089
      host: 0.0.0.0
    logging:
      level:
        org.springframework: INFO
        com.mkyong: DEBUG
    spring:
      cloud:
        config:
          enabled: false
      profiles:
        active: fsa23
      main:
        banner-mode: log