kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: accounts-web-ingress
  namespace: workshop
  # annotations:
    # nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fsa23web.northeurope.cloudapp.azure.com
  rules:
    - host: fsa23web.northeurope.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: accounts-web-service
                port:
                  number: 8081