apiVersion: v1
kind: Service
metadata:
  name: accounts-web-service
  namespace: workshop
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: accounts-web
  type: ClusterIP
  