apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-web-config-map
  namespace: workshop
data:
  application.yml: |-
    server:
      port: 8081
    logging:
      level:
        org.springframework: INFO
        com.mkyong: DEBUG
    spring:
      cloud:
        config:
          enabled: false
      profiles:
        active: fsa23
      integration:
        backend: "http://accounts-application-service:8089"





        

        